### ISSUE TITLE
bug: segment-region produce empty OrderedGroup

### ISSUE THREAD

**Issue by tboenig** [OCR-D/ocrd_tesserocr#115]
```xml
 <pc:ReadingOrder>
            <pc:OrderedGroup id="reading-order"/>
  </pc:ReadingOrder>
```
It is required that one of these elements into the ReadingOrder container.
See the schema snippet:
```xml
<choice minOccurs="1" maxOccurs="unbounded">
    <element name="RegionRefIndexed" type="pc:RegionRefIndexedType"/>
    <element name="OrderedGroupIndexed" type="pc:OrderedGroupIndexedType"/>
    <element name="UnorderedGroupIndexed" type="pc:UnorderedGroupIndexedType"/>
</choice>
```

**Comment by bertsky** [comment]
@tboenig please elaborate: What exactly did you do to arrive at an empty `OrderedGroup`?

Clearly, `ocrd-tesserocr-segment-line` has nothing to do with this.

In contrast, `ocrd-tesserocr-segment-region` does add/modifiy the reading order, but it usually adds a `RegionRefIndexed` for every region Tesseract finds. 

The exact behaviour depends on whether or not your input document already had region and region order annotations, whether or not `overwrite_regions` was enabled, and how good or bad Tesseract performs. In particular, if Tesseract does _not_ find any regions whatsoever (which so far I have never encountered), then yes, there will be an empty `OrderedGroup`.

**Comment by tboenig** [comment]
@bertsky ``Clearly, ocrd-tesserocr-segment-line has nothing to do with this.``

that's not true: after the segmentation the processor get always an readingOrder. But have you an empty page, the processor also generates a ReadingOrder, in this case an empty ReadingOrder, but this is not according to the scheme.

**Comment by bertsky** [comment]
You are mistaken: **line segmentation** does not deal with reading order (at all). Please change the title of the issue!

Also, please answer my question: what exactly did you do (ideally with example image).

If this is really just about an empty region segmentation, then the fix is trivial. But that's not entirely clear by your description.

**Comment by tboenig** [comment]
@bertsky new title.

description: I have an empty page without regions and the processor generates a ReadingOrder, in this case an empty ReadingOrder, but this is not according to the scheme.

**Comment by bertsky** [comment]
@tboenig please try with #116 and add a review there.

You can checkout and install PR branches like so:

    git fetch origin pull/116/head:pr-116
    git checkout pr-116
    pip install .

Just don't forget to revert to master when you are done testing:

    git checkout master
    git branch -d pr-116
    git pull
