### ISSUE TITLE
pip install ocrd_tesserocr error 

### ISSUE THREAD

**Issue by WeiHin** [OCR-D/ocrd_tesserocr#117]
When i run PIP install ocrd_tesserocr, i got the error as below:

![image](https://user-images.githubusercontent.com/61271158/75531575-0e79c900-5a4f-11ea-83fe-a3feb99e48a6.png)

But i had install libleptonica-dev

![image](https://user-images.githubusercontent.com/61271158/75532553-54cf2800-5a4f-11ea-9a1d-cdf4ff51e674.png)

and install tesserocr-2.4.0-cp37-cp37m-win_amd64.whl"

![image](https://user-images.githubusercontent.com/61271158/75532909-6d3f4280-5a4f-11ea-847b-c7cd0ddd6424.png)

problem is still cannnot be resolved

**Comment by bertsky** [comment]
Please read the [documentation](https://github.com/OCR-D/ocrd_tesserocr#installation) for installation procedure and requirements.

And please, no screenshots (but textual reports)!

**Comment by WeiHin** [comment]
thanks
