### ISSUE TITLE
Convert tests to pytest and fix `make coverage`

### ISSUE THREAD

**Issue by kba** [OCR-D/ocrd_tesserocr#198]

**Comment by bertsky** [comment]
What do you mean, convert to pytest?

I am surprised that our CI does not run `make test`, only `make cli-test`:
https://github.com/OCR-D/ocrd_tesserocr/blob/476be92b8b247b14502f9efbf7122c48501c3c2d/.circleci/config.yml#L29

What do you mean, fix make coverage?

To increase the coverage tests?
