### ISSUE TITLE
Incorrect model path with current master

### ISSUE THREAD

**Issue by mikegerber** [OCR-D/ocrd_tesserocr#202]
With current master (possible the same as the current release), and an install like this:

```
make install-tesseract
make deps
make install
```

I get this as the model path (aka "module dir" or "module resource location"):

```
❯ ocrd-tesserocr-recognize -D
./
```

I've asked @bertsky in the OCR-D/Lobby, and tried PR #200 -> That gives the correct path:

```
❯ ocrd-tesserocr-recognize -D
/home/b-mg106/.pyenv/versions/3.11.7/envs/ocrd_tesserocr/share/tessdata/
```

**Comment by mikegerber** [comment]
Possibly useful for debugging:

`python -c "import tesserocr; print(tesserocr.get_languages()[0])"` gives the same paths. In an earlier test -- I think -- at least `tesseract --list-langs` gave the correct languages for the broken installation.

**Comment by mikegerber** [comment]
` dpkg -l | grep tesser` is empty.

**Comment by bertsky** [comment]
> ` dpkg -l | grep tesser` is empty.

That's because we always build our own Tesseract from src now, to be on the safe side.

Since #200 already fixed this, and has been merged, can we close @mikegerber ?

**Comment by mikegerber** [comment]
> > ` dpkg -l | grep tesser` is empty.
> 
> That's because we always build our own Tesseract from src now, to be on the safe side.

I commented that to document that the system does not have any other Tesseract besides the one installed using `make install-tesseract`.

> Since #200 already fixed this, and has been merged, can we close @mikegerber ?

I think so!
