### ISSUE TITLE
ocrd resmgr same comment for 2 tesseract models

### ISSUE THREAD

**Issue by jbarth-ubhd** [OCR-D/ocrd_tesserocr#210]
- frak2021.traineddata  (https://ub-backup.bib.uni-mannheim.de/~stweil/tesstrain/frak2021/tessdata_best/frak2021-0.905.traineddata)
  **Tesseract LSTM model based on Austrian National Library newspaper data**

- ONB.traineddata  (https://ub-backup.bib.uni-mannheim.de/~stweil/ocrd-train/data/ONB/tessdata_best/ONB_1.195_300718_989100.traineddata)
  **Tesseract LSTM model based on Austrian National Library newspaper data**

**Comment by bertsky** [comment]
Fixed via 75a782d
