### ISSUE TITLE
new locale assertions in Tesseract are incompatible with Click

### ISSUE THREAD

**Issue by bertsky** [OCR-D/ocrd_tesserocr#23]
Ever since Tesseract 4 had to [introduce an assertion](https://github.com/tesseract-ocr/tesseract/issues/1670) that localization be plain POSIX (`C`) to ensure certain legacy assumptions in its code are always met, we have to override the current locale before initializing `tesserocr` API, too. This cannot be done by the user before calling any `ocrd_tesserocr` CLI, because we  depend on the Click library, which itself is [incompatible](http://click.palletsprojects.com/en/7.x/python3/#python-3-surrogate-handling) (in Python 3) with that locale (it requires at least `C.UTF-8`). So we have a deadlock.

We could perhaps reset the locale _after_ `click` and _before_ `tesserocr` though.

**Comment by kba** [comment]
So the tests work because they use the `ocrd_tesserocr` API directly, right? I ran into that encoding issue with different CI platforms, yes we need to override `LC_*` after loading click. We should add tests that use the CLI as well. I'll look into it.

**Comment by kba** [comment]
Oh you fixed it already. Self-fixing issues are the best issues :+1:

**Comment by bertsky** [comment]
No, the tests (presumably) still work, because they use an older Tesseract version without the assertion in place. True, we should add a CLI test (as in core/test/test_cli.py)...

**Comment by kba** [comment]
> No, the tests (presumably) still work, because they use an older Tesseract version without the assertion in place.

They did fail before but we set the locale to `C` before running the tests

https://github.com/OCR-D/ocrd_tesserocr/blob/master/.travis.yml#L32

**Comment by bertsky** [comment]
Oh, I see. I was distracted by my (non-container) test results.
