### ISSUE TITLE
Allow the use of multiple models (at once)

### ISSUE THREAD

**Issue by wrznr** [OCR-D/ocrd_tesserocr#37]
Tesseract allows for recognition with multiple models at once via the `+` operator:
```shell
$ tesseract 1930.cropped.jpg 1930 -l Fraktur+Latin
```
The same is not possible yet with `ocrd_tesserocr`. Using
```json
{
  "model" : "Fraktur+Latin"
}
```
leads to
```
Exception: configured model Fraktur+Latin is not installed
```
Pls. note that `tesserocr` is able to interpret the `+` operator.

**Comment by stweil** [comment]
While it is fine to support the native syntax of Tesseract, it might be good to support an additional syntax which is independent of the OCR software. "model" could for example not only allow a string value, but also an array of strings in JSON.
