### ISSUE TITLE
Any need for libxml2-utils and libimage-exiftool-perl

### ISSUE THREAD

**Issue by kba** [OCR-D/ocrd_tesserocr#42]
In Makefile:

```make
deps-ubuntu:
   apt-get update
   apt-get install -y \
      libxml2-utils \
      libimage-exiftool-perl \
```

Are these just legacy or are there callouts to xmllint or exiftool?

cd1a0f91

**Comment by bertsky** [comment]
Yes, I think those can be removed. The `xmllint` dep (originally 281e31f1) has since been removed from core, and exiftool-perl (originally 401faf3d) probably once depended on pyexiftool (but that uses the CLI as backend, not Perl)...

**Comment by kba** [comment]
Dropped in https://github.com/OCR-D/ocrd_tesserocr/commit/12d2e2baa48f5f2ca002da634b79304ea2feb028#diff-b67911656ef5d18c4ae36cb6741b7965
