### ISSUE TITLE
sudo needed?

### ISSUE THREAD

**Issue by kba** [OCR-D/ocrd_tesserocr#43]
`sudo` is not available in many docker images. Default user within a docker container is root. The `deps-ubuntu` target is used only for building the docker container for dockerhub and circle ci. I see no need to have `sudo` in the makefile.

@bertsky ?

**Comment by bertsky** [comment]
Neither do I! And a user who wants to run this herself (interactively in the host OS) can do `sudo make deps-ubuntu` if she sees it fail in lack of privileges.
