### ISSUE TITLE
Use common functionalities from "ocrd-utils"

### ISSUE THREAD

**Issue by wrznr** [OCR-D/ocrd_tesserocr#49]
As soon as they are available, the common functionalities from `core` should be employed.

**Comment by bertsky** [comment]
Right, we should move `common` into core, but the image functions all depend on the workspace instance, so I think `ocrd.workspace.Workspace` would be the best place for them. (The coordinate conversion functions should of course go to `ocrd_utils`.)

**Comment by kba** [comment]
Most of the `ocrd_*` modules have their own `utils` modules that are too specific for `ocrd_utils`. 

For the `image_from_*` functions, it would indeed make most sense to have them in workspace as you proposed.

**Comment by bertsky** [comment]
Splendid. Just note, I will add a PR in ocrd_tesserocr which will rebase everything in `common` on true polygons (and masking instead of cropping). We should wait for that version in core.

**Comment by kba** [comment]
Has been implemented as of https://github.com/OCR-D/ocrd_tesserocr/pull/66
