### ISSUE TITLE
locale setting for tesserocr does not work on ubuntu 19.04

### ISSUE THREAD

**Issue by hnesk** [OCR-D/ocrd_tesserocr#78]
Here:
https://github.com/OCR-D/ocrd_tesserocr/blob/1ba854016e0651e93b94b7c060314a533bf0446d/ocrd_tesserocr/__init__.py#L7
the locale should be set to `C.UTF-8`, but this doesn't work because the locale `C.UTF-8` gets aliased to `en_US.UTF-8` (at least on my ubuntu 19.04 system, see below)

Afterwards the import here:
https://github.com/OCR-D/ocrd_tesserocr/blob/1ba854016e0651e93b94b7c060314a533bf0446d/ocrd_tesserocr/recognize.py#L4
fails with the good old:

`!strcmp(locale, "C"):Error:Assert failed:in file baseapi.cpp, line 209`

The alias comes from the file:
`/usr/share/X11/locale/locale.alias`
In line 63:
`C.UTF-8                                 en_US.UTF-8`

This is the default as can be seen here:

https://github.com/mirror/libX11/blob/87c77a1e6d7034536e9d25ce24a667ebf53486a7/nls/locale.alias.pre#L18

**Comment by bertsky** [comment]
The alias is not the problem. (It's the same on my system, but works.) But you probably don't have the locale installed (with _localedef_) that it points to (`en_US.UTF-8`).

Could you please verify that? (By running `localedef --list-archive`)

**Comment by hnesk** [comment]
The locale is there:
```bash
$ localedef --list-archive
de_AT.utf8
de_BE.utf8
de_CH.utf8
de_DE.utf8
de_IT.utf8
de_LI.utf8
de_LU.utf8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IL
en_IL.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
```
Digging a bit deeper I found the alias set in /usr/lib/python3.7/locale.py (around line 938) on my system. Parts of the file are generated from the mentioned  `/usr/share/X11/locale/locale.alias`. 
I wonder how this can differ on different systems: For me the locale C.UTF-8 aliases to en_US.UTF-8 in python2.7 / 3.7 / 3.8 according to locale.py and this test script:

```python
import locale
locale.setlocale(locale.LC_ALL, 'C.UTF-8')
print(locale.getlocale(locale.LC_CTYPE))
```
To solve this would be a workaround (setting the C locale a way my python interpreter get's it) around workaround (tesseract<4.1 doesn't work with any locale except C), so let's leave it as it is, especially when Ubuntu 19.10 with tesseract 4.1 is just around the corner.
