### ISSUE TITLE
documentation: transform README.rst to README.md

### ISSUE THREAD

**Issue by tboenig** [OCR-D/ocrd_tesserocr#81]
Please transform your README file to markdown file format and check it for completeness. 
Thank you very much.

**Comment by bertsky** [comment]
I can do that (using pandoc). But really? Why not rST? You are going to need rST import anyway when capturing the rich docstrings of Python source code.

**Comment by bertsky** [comment]
Fixed by #82.

> > You are going to need rST import
> 
> You mean for generating apidocs with sphinx? sphinx supports markdown by extension, so that wouldn't be a problem.

Are you suggesting we should also convert our rST docstrings? (rST is recommended by PEP 287.)

**Comment by kba** [comment]
> Fixed by #82.

🙇 

> Are you suggesting we should also convert our rST docstrings? (rST is recommended by PEP 287.)

No.
