### ISSUE TITLE
README: Use unofficial Tesseract4 PPA

### ISSUE THREAD

**Issue by cneud** [OCR-D/ocrd_tesserocr#88]
Mention https://launchpad.net/~alex-p/+archive/ubuntu/tesseract-ocr

**Comment by cneud** [comment]
https://github.com/OCR-D/ocrd_tesserocr/pull/90

**Comment by kba** [comment]
Fixed in https://github.com/OCR-D/ocrd_tesserocr/commit/e3151a544eab20a29703d411b93c2714fb97df3c
