### ISSUE TITLE
add 1 to right/lower end of bboxes from Tesseract

### ISSUE THREAD

**Issue by bertsky** [OCR-D/ocrd_tesserocr#93]
Cf. https://github.com/OCR-D/core/commit/4192ba5781682319e60c0c175bcac26c91c9ab47#commitcomment-35833282

**Comment by stweil** [comment]
The result of the discussion was, that PAGE and Tesseract use the same convention for `bbox`, so I think that this issue can be closed.

**Comment by kba** [comment]
Thanks for clarifying @bertsky @stweil
