### ISSUE TITLE
PAGE xml Word tokenization

### ISSUE THREAD

**Issue by M3ssman** [OCR-D/ocrd_tesserocr#99]
Hello Community,

I've encountered unexpected behavior using ocr-tesserocr-recognize on Word-Level using Parameter `textequiv_level`, which seems to run into trouble finding correct word boundaries
and therefore messes data on word-level

[ulb-dd-zeitungsdigitalisierung-02.zip](https://github.com/OCR-D/ocrd_tesserocr/files/3926851/ulb-dd-zeitungsdigitalisierung-02.zip)

## Actually

```xml
    <pc:TextLine id="region0035_line0026">
        <pc:Coords points="405,2412 2485,2412 2485,2508 405,2508"/>
        <pc:Word id="region0035_line0026_word0000">
            <pc:Coords points="405,2412 523,2412 523,2508 405,2508"/>
            <pc:TextEquiv conf="0.59">
                <pc:Unicode>ſind</pc:Unicode>
            </pc:TextEquiv>
        </pc:Word>
        <pc:Word id="region0035_line0026_word0001">
            <pc:Coords points="538,2412 693,2412 693,2508 538,2508"/>
            <pc:TextEquiv conf="0.96">
                <pc:Unicode>mehr</pc:Unicode>
            </pc:TextEquiv>
        </pc:Word>
        <pc:Word id="region0035_line0026_word0002">
            <pc:Coords points="727,2412 915,2412 915,2508 727,2508"/>
            <pc:TextEquiv conf="0.95">
                <pc:Unicode>pikant</pc:Unicode>
            </pc:TextEquiv>
        </pc:Word>
        <pc:Word id="region0035_line0026_word0003">
            <pc:Coords points="933,2412 1445,2412 1445,2508 933,2508"/>
            <pc:TextEquiv conf="0.95">
                <pc:Unicode>als regelmäßig,</pc:Unicode>
            </pc:TextEquiv>
        </pc:Word>
        <pc:Word id="region0035_line0026_word0004">
            <pc:Coords points="1452,2412 1951,2412 1951,2508 1452,2508"/>
            <pc:TextEquiv conf="0.94">
                <pc:Unicode>der Teint ihres</pc:Unicode>
            </pc:TextEquiv>
        </pc:Word>
        <pc:Word id="region0035_line0026_word0005">
            <pc:Coords points="1972,2412 2485,2412 2485,2508 1972,2508"/>
            <pc:TextEquiv conf="0.08">
                <pc:Unicode>„Gefichtes blei,</pc:Unicode>
            </pc:TextEquiv>
        </pc:Word>
        <pc:TextEquiv>
            <pc:Unicode>ſind mehr pikant als regelmäßig, der Teint ihres „Gefichtes blei,</pc:Unicode>
        </pc:TextEquiv>
    </pc:TextLine>
```

## Expected 

```xml
 <pc:Word id="region0035_line0026_word0003">
            <pc:Coords points="933,2412 1445,2412 1445,2508 933,2508"/>
            <pc:TextEquiv conf="0.95">
                <pc:Unicode>als</pc:Unicode>
            </pc:TextEquiv>
        </pc:Word>
        <pc:Word id="region0035_line0026_word0004">
            <pc:Coords points="1452,2412 1951,2412 1951,2508 1452,2508"/>
            <pc:TextEquiv conf="0.94">
                <pc:Unicode> regelmäßig,</pc:Unicode>
            </pc:TextEquiv>
        </pc:Word>
```

## Plattform

Ubuntu 18.04 LTS
tesseract 4.1.1-rc2-17-g6343
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found AVX2
 Found AVX
 Found FMA
 Found SSE
 Found libarchive 3.2.2 zlib/1.2.11 liblzma/5.2.2 bz2lib/1.0.6 liblz4/1.7.1

**Comment by bertsky** [comment]
Hi @M3ssman,

thanks for your report!

As just pointed out in the chat, this happens when you enter recognition with existing word segmentation (in your case, from the rule-based `ocrd-tesserocr-segment-word` step before).

You can either use `ocrd-tesserocr-recognize` parameter `overwrite_words=True`, or not run word segmentation before recogition in your pipeline.

**Comment by M3ssman** [comment]
Thanks for your fast replies, too!

This is the last script snippet I used to run the pipeline, containing the remarks with `overwrite_words` (please note, the one in [ulb-dd-zeitungsdigitalisierung-02.zip](https://github.com/OCR-D/ocrd_tesserocr/files/3926851/ulb-dd-zeitungsdigitalisierung-02.zip) is not up-to-date)

```
#!/bin/bash

START=OCRD-IMG
SCAN_FILE=1681877805_J_0001_1536
SCAN_FILE_PATH=data/${SCAN_FILE}.tif

rm mets.xml
ocrd workspace init .
ocrd workspace add -G ${START} -i ${SCAN_FILE} -m image/tif -g ${SCAN_FILE} ${SCAN_FILE_PATH}

ocrd-tesserocr-segment-region -I ${START} -O REGIONS -m mets.xml
ocrd-tesserocr-segment-line -I REGIONS -O LINES -m mets.xml 
ocrd-tesserocr-segment-word -I LINES -O WORDS -m mets.xml 

INPUT_TSR_RECOGNIZE=WORDS
ocrd-tesserocr-recognize -I ${INPUT_TSR_RECOGNIZE} -O TEXT -p '{"model": "frk", "textequiv_level": "word", "overwrite_words" : true }' -m mets.xml
```

**Comment by bertsky** [comment]
This is strange. `ocrd-tesserocr-recognize` created text results correctly (including tokenization), but PageViewer does not show us any text (on no hierarchy level).

Here's an excerpt of `region0035` (which gets concatenated from the lines) by the processor:

<PRE> en tagtäglich in die Maſſe „werfen l Eien
Wi freiburger Brofeſſors Alban Stolz von dem „Finger
gottes" iſt bekannt. Wie der wunderfüchtige Herx den folgenden,
im in Amſtetten ereigneten Fall in ſein Syſtem einreihen
fd, darauf darf man billig neugierig ſein. Cin Bauer dieſes Orts
"hm aus der Sparkaſſe von Waidhofen eine dort von ihm einge-
fegte Summe von 40,800 ft. heraus, um ſie einem lobwürdigen wei?
Jen Orden, der ſich in Amſtetten ein Ordenshaus bauen will, zu
dieſem Behufe zu ſchenken. Kaum hatte der Bauer die Banknoten
im Hauſe, als daſelbſt der Blitz einſchlug und das Geld verbrannte.
erden, die „Frommen auch in, dieſem verhängmßvollen Olibſchlage
ven befannten „Finger Gottes" erbliken ? =- Aus Oberhejjen
wird berichtet, daß unter. den Katholiken dex Wetterau in Fulda
geoeneteSireiiare in Umtanfgejeht: find, weiche umTieve5ga eu
URSS TTEeN VE... ee u 2220028
ür ine berühmte Schönheit in berliner Hoffreiſen,] die Gräfin
Yoſefine v. Seydewib, geb. den 29. November 1839, hat fich ſoeben
"nit dem Grafen Karl v. Dönhoff, geb. 26. Zanuar 1845, verlobt.
Seit länger als zwölf Jahren war die Braut Hofdame bei der
Prinzeſſin Karl und erregte überall Berwunderung durch) hre eigen-
Prinze Schönheit. Sogar am Hofe der Kaiſerin Eugenie machte ſie
Aufſehen. und. wurde von derfeiben als gefährliche Nevenbuhierin
um den Preis der Schönheit mißliebig betrachtet. Die Gräßin iſt
oine junoniſche Geſtalt, aber doh verbinden ji; Anmuth und Zart-
heit in ihrer Erſcheinung. Obwohl feit beinahe 10 Jahren über die
erſte Jugend, hinaus veſikt jie noch die Friſche derfeiben, ihre Züge
find mehr pikant als regelmäßig, der Teint ihres Geſichtes bleich,
das üppige Haar vom hellſten Aſchblond. Auf den Opernhausbällen
war ſie ſtets der Gegenſtand allgemeiner Aufimertſamieit für Free
und Einheimiſche. Jhr berühmter Onkel, Fürſt Pücler-Muskau
orflärte ſie für ſeine Liebling8-Nichte -- fie hat noch je&lt;s Schweſtern
- enterbte ffe aber dennoch et Flan veröffentlichter ve
-- [Die Bevölkerung der Welt.] Ein ſoeben veröffentlichter Be-
richt "des fiatiſtiſchen Bureaus an Waſhington enthält eine, inter
eſſante Tabelle über die Bevölkerung der Erde. Die Gejammt-
Bevölkerung der Erde iſt darin auf 1.391,032,000 Seelen angegeben.
Aſien, der vorkreichſte Welttheit . - enthält 798 Millionen, während
(Europa 309x Millionen, Afrika 203 Millionen, Amerika 843 Mill.
und Auſtralien und Polyneſien 44 Millionen Einwohner haben.
Die qrößtren Staaten Europas. ſind mit folgenden. Fiſſorn anze“
geben: Rußland 71 Millionen, das Deutiche Reich 41 Millionen,
Frankreich 36 Millionen Oeſterreich-Ungara 36 Millionen. Groß-
nitannien und Friand: 32 Millionen, Jiatien nahezu 27 Millionen,
Spanien 1634 Millionen und die Türkei nahezu 16 Millionen. Die
andern Länder überſteigen je nicht 5 Millionen. Jn Aſien iſt China,
das beiweitem das bevölkertſte Land der Erde iſt, mit 425 Millionen
(Einwohnern geſegnet, Hindoſtan mit 240 Millionen, Japan zählt
33 Millionen, die oſtindiſch&lt;en Inſeln 394 Millionen, Birma, Siam
und das ferner gelegene Jndien nahezu 26 Millionen, die ajiatiſche
Türkei 13x Millionen und das afiatiſche Rußland nahezu 11 Mill.
Die auſtraliſche Bevölkerung iſt mit 1,674,500 und die der polyne-
ſiſchen Inſeln incluſive Neu-Guinea und Neu-Seeland mit 2,76 3,500
Seelen angegeben. Jn Afrika find die Hauptaotheilungen: Wetzt-
Sudan und die mittelafritaniſche Region mit 89 Millionen, die
Central - Sudan - Region 39 Millionen, Südafrika 204 Yiillionen,
das Galla - Land und die Region öſtlich vom Weißen Nit 15 Bn.
Samauli 8 Millionen, Egypten 84 Millionen und Marokko 6
Millionen. "In Amerika befinden ich zwei Drittel der Bevölkerung
nördlich vom Jſthmus, während die Bereinigten Staaten nahezu
39 Millionen , Mexiko über 9 Millionen und die britiſchen Provin-
jen Millionen Einwohner haben. zie Geſamt. Vetrag
von Nordamerika iſt auf nahezu 52 Millionen und die von Sid-
amerifa auf 25 Miſlioſſen, von denen Draſiten 15 Zonen vi:
hält, angegeben. Die weſtindiſchen Jnfeln haben 4 YPüllionen und
die central = amerikaniſchen Staaten nicht ganz 3 Millionen Cin-
wohner: - Dieſen Tabellen zufolge iſt Vondon, mit men Ei
wohnern die volkreichſte Stadt der Welt, während Philadelphia mit
674,022 Einwohnern (1870) die 18. Stadt im Punkt der Bevblte-
rung iſt. Die 18 Städte find ihrer Ordnung nach folgende: kXon-
don 3,254,260, Sutc&lt;an (China) 2,9000,900, Paris 1,851,792, Peking
],3900,090, Tſchantſchaufu 1,000,900, Hangtſ&lt;hau-fu 1,000,000, Si-
angton 1,900,000, Singnan-fu 1,000,000 , Canton 1,000,000 , New-
ot 242.208. (Etemtite 900.000, Wien 854,2817 Berſit HWIU,
Hangkau 300,000, Tſchingtu-fu 890,000, Calcutta 794,649, Tokio
(21060) 674,448, und Pyiladelpia 674,09 Einwohner. Don, Std-
ten kleinex als Philadelphia find die leitenden folgende: St. Pe-
ter3burg 667,963, Bombay 644,405, Moskau 611,970, Conjtan-
tinopel 600,060, Gla8gow 547,538, Liverpool 493405 und YYiio de
„Faneiro 420.000 Einwohner.
-- [Lachſe.] Dem deutſchen Fiſcherei-Verein wird die erfreuliche
Thatſache gemeldet, daß der La&lt;hs namentlich im Ojten der pom-
merſhen, jowie der-preußiſchen Küſte fich zahlreich vorgeſunden have,
nnd daß 3. B. in Klein-Kuhren nach ſtattgefnndener Aufzeichnung</PRE>

This is not very good, but your image is challenging and the workflow too simple. (You'd need at least a better binarization than Tesseract's internal one, probably followed by denoising, then clipping of neighbouring regions, followed by polygon-based line segmentation, then dewarping.)

As for PageViewer, the XML validates, so I can only guess that the image is too large for the program, or the annotation too complex. But I don't see any errors or warnings (not even on stdio).

Maybe we should report this on https://github.com/PRImA-Research-Lab/prima-page-viewer?

**Comment by bertsky** [comment]
@M3ssman can we close here?

**Comment by M3ssman** [comment]
@bertsky Yes, we can close.
